GET http://localhost:3000/members

###
GET http://localhost:3000/members/682a474f9d7fa815377974cb


###
POST  http://localhost:3000/members
Content-Type: application/json

{
  "firstname":"Delaney",
  "lastname": "leke",
  "email":"uelaneyzingwa@gmial.com",
  "password":"31425698"
}

###

DELETE http://localhost:3000/members/683eee0c1906e984423287e1


###
PATCH  http://localhost:3000/members/682a474f9d7fa815377974cb
Content-Type: application/json

{
  "name": "John D"
}
